"""Alembic environment.

Reads the connection string from the application settings rather than
alembic.ini, so migrations and the running app can never target different
databases.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig
from typing import Any

from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config
from sqlalchemy.pool import NullPool

from alembic import context
from app.core.config import get_settings

# Importing app.models populates Base.metadata with every ORM model.
from app.models import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

settings = get_settings()
if settings.database_dsn is None:
    raise RuntimeError(
        "DATABASE_URL is not set. Alembic needs a database connection string; "
        "copy .env.example to .env and set DATABASE_URL to your Supabase URL."
    )

# `%` is an interpolation sigil in alembic.ini; passwords routinely contain one.
config.set_main_option("sqlalchemy.url", settings.database_dsn.replace("%", "%%"))

# Tables owned by PostGIS and Supabase's own schemas. Without this filter,
# autogenerate proposes dropping them because they are absent from our metadata.
EXCLUDED_TABLES = {
    "spatial_ref_sys",
    "geography_columns",
    "geometry_columns",
    "raster_columns",
    "raster_overviews",
}
EXCLUDED_SCHEMAS = {
    "auth",
    "storage",
    "extensions",
    "graphql",
    "graphql_public",
    "realtime",
    "supabase_functions",
    "vault",
    "pgbouncer",
    "tiger",
    "tiger_data",
    "topology",
}


def include_object(
    obj: Any,
    name: str | None,
    type_: str,
    reflected: bool,
    compare_to: Any,
) -> bool:
    """Keep PostGIS and Supabase-managed objects out of autogenerated diffs."""
    if type_ == "table":
        if name in EXCLUDED_TABLES:
            return False
        schema = getattr(obj, "schema", None)
        if schema in EXCLUDED_SCHEMAS:
            return False
    return True


def _configure(connection: Connection | None = None, url: str | None = None) -> None:
    context.configure(
        connection=connection,
        url=url,
        target_metadata=target_metadata,
        include_object=include_object,
        include_schemas=False,
        compare_type=True,
        compare_server_default=True,
        literal_binds=url is not None,
        dialect_opts={"paramstyle": "named"} if url is not None else {},
    )


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting to a database."""
    _configure(url=config.get_main_option("sqlalchemy.url"))

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    _configure(connection=connection)

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Connect and run migrations against a live database."""
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
