"""data foundation: postgis, stations, sensors, measurements, fires, weather

The first real schema. Enables PostGIS before any geometry column is created —
`CREATE EXTENSION` must precede the first `Geometry` type or the DDL fails on a
fresh database.

Hand-written rather than autogenerated: autogenerate wants to create PostGIS's own
`spatial_ref_sys` and the `idx_*` spatial indexes that `CREATE EXTENSION` and
GeoAlchemy2 manage for us.

Revision ID: 0002_data_foundation
Revises: 0001_baseline
Create Date: 2026-07-17
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

revision: str = "0002_data_foundation"
down_revision: str | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SRID = 4326


def upgrade() -> None:
    # Must come first: every geometry column below depends on it.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    op.create_table(
        "stations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("openaq_location_id", sa.BigInteger(), nullable=True),
        sa.Column("cpcb_station_name", sa.String(length=200), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("provider", sa.String(length=60), nullable=True),
        sa.Column("geom", Geometry("POINT", srid=SRID, spatial_index=True), nullable=False),
        sa.Column("first_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("openaq_location_id"),
    )
    op.create_index("ix_stations_openaq_location_id", "stations", ["openaq_location_id"])
    op.create_index("ix_stations_cpcb_station_name", "stations", ["cpcb_station_name"])
    op.create_index("ix_stations_city", "stations", ["city"])
    op.create_index("ix_stations_provider", "stations", ["provider"])
    op.create_index("ix_stations_source", "stations", ["source"])
    op.create_index("ix_stations_city_provider", "stations", ["city", "provider"])

    op.create_table(
        "sensors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("openaq_sensor_id", sa.BigInteger(), nullable=True),
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("parameter", sa.String(length=30), nullable=False),
        sa.Column("units", sa.String(length=20), nullable=True),
        sa.Column("datetime_first", sa.DateTime(timezone=True), nullable=True),
        sa.Column("datetime_last", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["station_id"], ["stations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("openaq_sensor_id"),
        sa.UniqueConstraint("station_id", "parameter", "openaq_sensor_id", name="uq_sensor_identity"),
    )
    op.create_index("ix_sensors_openaq_sensor_id", "sensors", ["openaq_sensor_id"])
    op.create_index("ix_sensors_station_id", "sensors", ["station_id"])
    op.create_index("ix_sensors_parameter", "sensors", ["parameter"])
    op.create_index("ix_sensors_source", "sensors", ["source"])
    op.create_index("ix_sensors_param_span", "sensors", ["parameter", "datetime_first", "datetime_last"])

    op.create_table(
        "measurements",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("sensor_id", sa.Integer(), nullable=True),
        sa.Column("parameter", sa.String(length=30), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("units", sa.String(length=20), nullable=True),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["station_id"], ["stations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sensor_id"], ["sensors.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        # Makes re-running an ingest idempotent.
        sa.UniqueConstraint("station_id", "parameter", "measured_at", "source", name="uq_measurement_identity"),
    )
    op.create_index("ix_measurements_station_id", "measurements", ["station_id"])
    op.create_index("ix_measurements_sensor_id", "measurements", ["sensor_id"])
    op.create_index("ix_measurements_parameter", "measurements", ["parameter"])
    op.create_index("ix_measurements_measured_at", "measurements", ["measured_at"])
    op.create_index("ix_measurements_source", "measurements", ["source"])
    op.create_index(
        "ix_measurements_station_param_time", "measurements", ["station_id", "parameter", "measured_at"]
    )
    op.create_index("ix_measurements_param_time", "measurements", ["parameter", "measured_at"])

    op.create_table(
        "fire_detections",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("geom", Geometry("POINT", srid=SRID, spatial_index=True), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("brightness_k", sa.Float(), nullable=True),
        sa.Column("frp_mw", sa.Float(), nullable=True),
        sa.Column("confidence", sa.String(length=10), nullable=True),
        sa.Column("satellite", sa.String(length=20), nullable=True),
        sa.Column("instrument", sa.String(length=20), nullable=True),
        sa.Column("daynight", sa.String(length=1), nullable=True),
        sa.Column("scan", sa.Float(), nullable=True),
        sa.Column("track", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("geom", "acquired_at", "source", name="uq_fire_detection_identity"),
    )
    op.create_index("ix_fire_detections_acquired_at", "fire_detections", ["acquired_at"])
    op.create_index("ix_fire_detections_confidence", "fire_detections", ["confidence"])
    op.create_index("ix_fire_detections_source", "fire_detections", ["source"])

    op.create_table(
        "weather_observations",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("geom", Geometry("POINT", srid=SRID, spatial_index=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("temperature_c", sa.Float(), nullable=True),
        sa.Column("relative_humidity_pct", sa.Float(), nullable=True),
        sa.Column("wind_speed_ms", sa.Float(), nullable=True),
        sa.Column("wind_direction_deg", sa.Float(), nullable=True),
        sa.Column("boundary_layer_height_m", sa.Float(), nullable=True),
        sa.Column("precipitation_mm", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("geom", "observed_at", "source", name="uq_weather_identity"),
    )
    op.create_index("ix_weather_observations_observed_at", "weather_observations", ["observed_at"])
    op.create_index("ix_weather_observations_source", "weather_observations", ["source"])


def downgrade() -> None:
    op.drop_table("weather_observations")
    op.drop_table("fire_detections")
    op.drop_table("measurements")
    op.drop_table("sensors")
    op.drop_table("stations")
    # PostGIS is left installed: other schemas may depend on it, and dropping an
    # extension is not the inverse of the CREATE ... IF NOT EXISTS above.
